#!/bin/bash
task_name="$1"
container_name="crawler_$task_name"

docker rm -fv $container_name

docker run -d \
--user $(id -u):$(id -g) \
--name $container_name \
-e ROCKETSCRAPE_API_KEY=${ROCKETSCRAPE_API_KEY} \
apricoot/crawler:latest -- --jobId=$task_name

docker logs -f $container_name
